### ISSUE TITLE
[question] frontend plugins should use 'dom' instead of 'webworker'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse/theia-generator-plugin#20]
I believe the following snippet is incorrect:

https://github.com/eclipse/theia-generator-plugin/blob/bd5837244de06c1c29e5b8fdd1e41fb1f6ab53a8/templates/base/tsconfig.json#L11-L19

Despite declaring a plugin as `frontend` or `backend` the `compilerOptions` always uses `webworker` which does not have any access to `dom` elements (potential reason for https://github.com/eclipse/theia-generator-plugin/issues/19)

I don't believe `frontend` and `backend` plugins are properly defined by the generator.

**Comment by benoitf** [comment]
there is no access to dom from a VS Code extension/plugin

**Comment by benoitf** [comment]
`Window` object for example should not be available

**Comment by vince-fugnitto** [comment]
@benoitf 

It will fail building when attempting to resolve the types.
For instance the `Comment` (#19)
- perform `yo @theia/plugin`
- select "backend" plugin
- select "hello world" example

```
node_modules/@theia/plugin/src/theia.d.ts(8157,19): error TS2304: Cannot find name 'Comment'.
node_modules/@theia/plugin/src/theia.d.ts(8312,80): error TS2304: Cannot find name 'Comment'.

```

`Comment` comes from `lib.dom.ts`. 

---

If it's the case should we add the `skipLibCheck` in the `tsconfig.json` to avoid build failures due to the declaration files?

**Comment by benoitf** [comment]
@vince-fugnitto It's just that some definitions are missing

**Comment by vince-fugnitto** [comment]
Closing in favor of #19, thank you for clarifying @benoitf
